Techfest/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include('product.urls', namespace='product')),
]

product/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submit/(?P<pk>[0-9]+)/$', views.submit, name='submit'),
    url(r'^batch/(?P<pk>.*)/$', views.batch, name='batch'),
    url(r'^client/(?P<pk>.*)/$', views.client, name='client'),
]

product/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

class Industry(models.Model):
    title = models.CharField(max_length=30)
    def __str__(self):
        return self.title

class ClientType(models.Model):
    title = models.CharField(max_length=30)
    industry = models.ForeignKey(Industry, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Client(models.Model):
    title = models.CharField(max_length=30)
    clientType = models.ForeignKey(ClientType, on_delete=models.CASCADE)
    def __str__(self):
        return self.title


class ProductType(models.Model):
    title = models.CharField(max_length=50)
    industry = models.ForeignKey(Industry, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=30)
    productType = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    def __str__(self):
        return self.title

class RequiredDataTuple(models.Model):
    reqType = models.ForeignKey(ProductType, on_delete=models.CASCADE, related_name='required')
    identifier = models.CharField(max_length=30)
    fieldType = models.CharField(max_length=30)
    #fieldType is a choicefield in forms
    #productType/clientType appears on forms if fieldtype is set as product/client
    productType = models.ForeignKey(ProductType, null=True, blank=True)
    clientType= models.ForeignKey(ClientType, null=True, blank=True)

class BatchEntry(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT, editable=False)
    batch = models.CharField(max_length=100, editable=False)
    key = models.CharField(max_length=300, editable=False)

product/forms.py
from django import forms
from .models import RequiredDataTuple, Client, Product

class BatchForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(BatchForm, self).__init__(*args, **kwargs)

def generateForm(productType):
    dataset = RequiredDataTuple.objects.filter(reqType=productType)
    fields = {}
    for data in dataset:
        if data.fieldType == 'int':
            fields[data.identifier] = forms.IntegerField()
        elif data.fieldType == 'str':
            fields[data.identifier] = forms.CharField(max_length=200)
        elif data.fieldType == 'date':
            fields[data.identifier] = forms.DateField(widget=forms.SelectDateWidget)
        elif data.fieldType == 'datetime':
            fields[data.identifier] = forms.DateTimeField(widget=forms.DateTimeInput)
        elif data.fieldType == 'Product':
            choices =[]
            for product in Product.objects.filter(productType=data.productType):
                choices.append((product,str(product)))
            fields[data.identifier]=forms.ChoiceField(choices)
        elif data.fieldType == 'Client':
            choices = []
            for client in Client.objects.filter(clientType=data.clientType):
                choices.append((client,str(client)))
            fields[data.identifier]=forms.ChoiceField(choices)

    return type('BatchForm', (forms.Form,), fields)

product/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from . import models
from . import forms
from .blockchain.bigchain_connector import BlockChain

def index(request):
    return HttpResponse("Success")

def submit(request,pk):
    if request.method == 'POST':
        data = request.POST.dict()
        del data['csrfmiddlewaretoken']
        entry = models.BatchEntry()
        entry.batch = data['Batch ID']
        entry.product_id = pk
        db = BlockChain()
        handle = db.write({'data':data})
        entry.key = handle.get('id')
        entry.save()
        return HttpResponseRedirect(reverse('product:batch',args=[entry.key]))
    product = get_object_or_404(models.Product,pk=pk)
    productType = models.ProductType.objects.get(pk=product.productType.pk)
    form = forms.generateForm(productType)
    return render(request, 'submit.html', context={'form':form,'product':product})


def batch(request,pk):
    db= BlockChain()
    transaction = db.get_tx(key=pk)
    entry = models.BatchEntry.objects.get(key=pk)
    product = get_object_or_404(models.Product, pk=entry.product_id)
    data = transaction['asset']['data']
    keyValueList = []
    for key in data:
        li = str(key)+'  :   '+str(data[key])
        keyValueList.append(li)
    print(keyValueList)

    return render(request, 'batch.html', context={'batch':keyValueList, 'product':product})

def client(request,pk):
    client = get_object_or_404(models.Client, pk=pk)
    products = models.Product.objects.filter(client=client)
    return render(request, 'client.html', context={'client':client,'products':products})

product/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'product/style.css' %}" type="text/css"> </head>

<body>
  <nav class="navbar navbar-expand-md bg-primary navbar-dark" id="navbar-agrichain">
    <div class="container">
	    <a class="navbar-brand" href="#"><b> <img src="{% static 'product/images/logo_white.png' %}"></b></a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent" aria-controls="navbar2SupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span> </button>
      <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
	      <a class="btn navbar-btn btn-primary ml-2 text-white" href="{% url 'product:client' 1 %}"><i class="fa d-inline fa-lg fa-user-circle-o"></i>Your Business</a>
      </div>
    </div>
  </nav>
  <div class="pt-5">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
		<h1 class="">{% block title %}{% endblock %}
            <br> </h1>
        </div>
      </div>
    </div>
  </div>
  <div class="py-1">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
		{% block main %}
		{% endblock %}
        </div>
        <div class="col-md-4">
		{% block side %}
		{% endblock %}
		
	</div>
      </div>
    </div>
  </div>
  <script src="{% static 'https://code.jquery.com/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>

</html>

product/templates/batch.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{product.title}}{% endblock %}
{% block main %}
<ul>
	{% for k in batch%}
	<li>{{k}}</li>
	{% endfor %}
</ul>
{% endblock %}
{% block side %}
	<img src="{% static 'product/images/qrcode.png' %}" alt="QR Code">
{% endblock %}

product/templates/client.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{client.title}}{% endblock %}
{% block main %}
<ul>
  {% for product in products %}
  <li><a href="{% url 'product:submit' product.pk %}">{{product.title}}</a></li>
  {% endfor %}
</ul>
{% endblock %}
    

product/templates/submit.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Submit a new batch<br>
<h2>{{product.title}}</h2>
{% endblock %}
{% block main %}
    <form action="{% url 'product:submit' product.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p}}
	<div class="py-5">
          <div class="container">
            <div class="row">
              <div class="col-md-3">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Save</button>
              </div>
            </div>
          </div>
        </div>
     </form>
{% endblock %}
 